name: '👉 📦 Build Artifacts'

on:
  #   push:
  #     branches: [ main ]
  #   pull_request:
  #     branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Audit & Fix Dependencies
        run: npm audit fix
      - name: Build
        run: npm run build
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
